### ISSUE TITLE
ImportError: cannot import name _imaging

### ISSUE THREAD

**Issue by Greenaxio** [SpiderLabs/social_mapper#16]
```
Traceback (most recent call last):
  File "social_mapper.py", line 24, in <module>
    import face_recognition
  File "C:\Python27\lib\site-packages\face_recognition\__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "C:\Python27\lib\site-packages\face_recognition\api.py", line 3, in <module>
    import PIL.Image
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: cannot import name _imaging
```

**Comment by cclauss** [comment]
__python2 -m pip install --upgrade PIL__

**Comment by Greenaxio** [comment]
It throws this:

```
Could not find a version that satisfies the requirement PIL (from versions: )
No matching distribution found for PIL
```

**Comment by cclauss** [comment]
* __python2 -m pip uninstall PIL__
* __python2 -m pip pip install --upgrade Pillow__

**Comment by Greenaxio** [comment]
Didn't uninstall, because it wasn't installed in the first place.
Pillow is already up to date.

Sorry for being kinda dumb, I have almost no Python experience

**Comment by Greenaxio** [comment]
Just had to delete the PIL and Pillow directory in the site-packages.
And then reinstall Pillow

**Comment by Green-Wolf** [comment]
Hey @Greenaxio did you actually get it working on Windows in the end?

**Comment by Greenaxio** [comment]
@Green-Wolf that Error I fixed and my last Issue also. Now there are just errors with the script itself and not with outside stuff. But for now I do not have the time to tinker with it that much

**Comment by zimenglan-sysu-512** [comment]
hi @cclauss, this works for me.
```
sudo python3.6 -m pip uninstall PIL
sudo python3.6 -m pip install --upgrade Pillow
```
thanks.

**Comment by zimenglan-sysu-512** [comment]
hi @Green-Wolf 
it works in Jetson TX2 with python3.6

**Comment by Greenwolf** [comment]
@zimengalan-sysu-512 that’s really interesting to hear, would you mind sharing what steps you took to get it working with python 3.6?

**Comment by zimenglan-sysu-512** [comment]
hi @Green-Wolf 
i only to solve the problem `ImportError: cannot import name _imaging` which is not related to this repo by uninstall `PIL` and then reinstall it.
sorry about that
